version: '3.8'

services:
  backend:
    build: ./backend
    command: gunicorn lending.wsgi:application --bind 0.0.0.0:8000 --pythonpath lending
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8000:8000
    expose:
      - 8000
    env_file:
      - ./backend/.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./postgres/.env
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - API_SERVER=${ENV_API_SERVER}
    volumes:
      - react_static_volume:/usr/src/app/build/static
    ports:
      - 3000:3000
    expose:
      - 3000
    env_file:
      - .env
    command: serve -s build -l 3000
    depends_on:
      - backend
  nginx:
    restart: always
    build: ./nginx
    volumes:
      - react_static_volume:/usr/src/app/react_files/static
    ports:
      - 8008:80
    depends_on:
      - frontend

volumes:
  postgres_data:
  react_static_volume: