# Generated by Django 3.1.1 on 2022-02-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='category',
            field=models.CharField(blank=True, choices=[('Personal', 'Personal'), ('Business', 'Business'), ('Health', 'Health'), ('Other', 'Other')], max_length=25),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Denied', 'Denied'), ('Pending', 'Pending'), ('Processing', 'Processing')], max_length=25),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
